### ISSUE TITLE
Penthouse timed out after 30s

### ISSUE THREAD

**Issue by shibulijack-fd** [bezoerb/grunt-critical#20]
When I try to run the grunt task on a folder containing multiple HTML files, it runs for a few HTML files and after a while, I get this error:

**Penthouse timed out after 30s.**

This is my grunt config:

``` js
critical: {
    test: {
        options: {
            base: './',
            minify: true,
            width: 1280,
            height: 800
        },
        files: [
            {cwd: '.', src: ['build/en-US/**/*.html'], dest: 'compressed/'}
        ]
    }
}
```

**Comment by shibulijack-fd** [comment]
I fixed it by setting the timeout value to 120000 ms in penthouse index.js. It would be nice if we could set this value using options.

**Comment by ska-cz** [comment]
+1

**Comment by brendonboshell** [comment]
I have also been experiencing this issue. In my case, it turned out that I had some URLs for my test environment (of the form https://192.168.0.7, for example) that did not load under some environments and networks (even in Google Chrome they 'load' until they timed out). This is what was causing penthouse to timeout, so it is important that any external resources work in your HTML fixtures. Do you think this could be the issue you are seeing, too?

**Comment by bezoerb** [comment]
Penthouse options can be specified using the penthouse option. See https://github.com/addyosmani/critical#options
